homepage:
    pattern: /
    defaults: { _controller: BlockPuzzleBundle:Main:homepage }

single_new:
    pattern: /single/new
    defaults: { _controller: BlockPuzzleBundle:Single:new }

single_play:
    pattern: /single/play/{id}
    defaults: { _controller: BlockPuzzleBundle:Single:play }